version: "2"

linters:
  enable:
    - bodyclose
    - copyloopvar
    - durationcheck
    - errname
    - exptostd
    - misspell
    - modernize
    - nosprintfhostport
    - predeclared
    - reassign
    - recvcheck
    - usetesting
    - wastedassign
  settings:
    recvcheck:
      exclusions:
        - "*.UnmarshalJSON"
